[supervisorctl]
[supervisord]
nodaemon=true

[program:everest]
command=python3 main.py
autostart=true
autorestart=true
stdout_logfile=./log/supervisord_stdout.log
stdout_logfile_maxbytes=1024MB
redirect_stderr=true
startsecs=1
startretries=100
environment=